### ISSUE TITLE
ConvNeXt not compatible with Model wrapper

### ISSUE THREAD

**Issue by andreped** [andreped/GradientAccumulator#111]
**Describe the bug**
Seems like using the model wrapper, the model fails to load properly. Might be that this is fixed in later releases of `tensorflow`.

**To Reproduce**
Simply initialize a `ConvNeXt-Tiny` backbone, then use the model wrapper to add gradient accumulation support, and try to save and load the model. It should fail when loading.

**Expected behavior**

**Error logs/Screenshots**
```
Traceback (most recent call last):
  File "apps/train_fusion.py", line 319, in <module>
    main()
  File "apps/train_fusion.py", line 269, in main
    model = tf.keras.models.load_model(model_path + curr_time + "_" + curr_date + "_model_fusion_classifiers_" + name + "_fold_" + str(j), compile=False)
  File "/home/andrep/workspace/bcgrade/venv_latest/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/andrep/workspace/bcgrade/venv_latest/lib/python3.8/site-packages/tensorflow/python/trackable/base.py", line 205, in _method_wrapper
    result = method(self, *args, **kwargs)
TypeError: __init__() missing 2 required positional arguments: 'inputs' and 'outputs'
```

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu] Ubuntu
 - Version: [e.g. 20.04] 20.04
 - Python: [3.9] 3.8.10
 - TensorFlow: [2.8.0] 2.11.0

**Comment by andreped** [comment]
I tried running multiple tests, but I was unable to reproduce the issue based on the described instructions.

However, if you set the model name to `model.h5` or `model.keras`, which attempts to save the model in HDF5 format instead of saved model (saved model stores model as folder and HDF5 as single file), I am able to reproduce the `TypeError` seen above. Hence, that was likely what caused the issue.

However, when I tried to save the model in saved model format, I got another issue. Sadly, this happens regardless whether gradient accumulation is enabled or not, and it worked just fine if `ResNet50` is used.

It therefore appears that there is one or two bugs with the `ConvNeXt` in Keras which is causing this issue. Hence, this issue should be reported to the Keras team and not `GradientAccumulator`.

As this issue is outside the scope of this repo, I am closing this issue.

If anyone is interested in exploring this issue further, I made a [gist](https://colab.research.google.com/gist/andreped/09a7f599723ce1c5039c5270d646c956/convnext-gradient-accumulator-test.ipynb) that reproduces the issue.
