### ISSUE TITLE
Saving models to .h5 in tf>=2.8 fails

### ISSUE THREAD

**Issue by dbouget** [andreped/GradientAccumulator#18]
WARNING:tensorflow:Found duplicated `Variable`s 
in Model's `weights`. This is usually caused by `Variable`s being shared by Layers in the Model. These `Variable`s will be treated as separate `Variable`s when the Model is restored. To avoid this, please save w
ith `save_format="tf"`.
Traceback (most recent call last):
  File "train.py", line 230, in <module>
    model.fit(
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/h5py/_hl/group.py", line 149, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/h5py/_hl/dataset.py", line 142, in make_new_dset
    dset_id = h5d.create(parent.id, name, tid, sid, dcpl=dcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 87, in h5py.h5d.create
ValueError: Unable to create dataset (name already exists)

**Comment by andreped** [comment]
I was able to reproduce the error, by using `.h5` when saving the model in a unit test:
https://github.com/andreped/GradientAccumulator/runs/7013532197?check_suite_focus=true

**Comment by andreped** [comment]
Hmm, seems like this works just fine in TF 2.6.2, as seen from this CI job:
https://github.com/andreped/GradientAccumulator/runs/7013531511?check_suite_focus=true

But for newer versions of TF it fails. I read that they encourage us to use the SavedModel format instead of the old possibly-soon-deprecated HDF5 format.

So perhaps we should just avoid having HDF5 format support here, and instead focus on getting the other stuff working properly? I will refactor the stuff I did now and remove the .h5 test.
