### ISSUE TITLE
TensorFlow import issues in CI

### ISSUE THREAD

**Issue by andreped** [andreped/GradientAccumulator#48]
In a recent CI, it was observed that `tensorflow` failed to import due to `protobuf`.

This failed on both Python 3.8 and 3.9, with `tensorflow==2.8.0` on Ubuntu 20.04.

Might be that we have to introduce a strict versioning on `protobuf` during `tensorflow` installation.

```
2023-04-12 09:52:22.545216: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.[8](https://github.com/andreped/GradientAccumulator/actions/runs/4676953980/jobs/8283906385#step:7:9).16/x64/lib
2023-04-12 0[9](https://github.com/andreped/GradientAccumulator/actions/runs/4676953980/jobs/8283906385#step:7:10):52:22.545242: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/GradientAccumulator/GradientAccumulator/gradient_accumulator/__init__.py", line 1, in <module>
    from .accumulators import GradientAccumulateOptimizer
  File "/home/runner/work/GradientAccumulator/GradientAccumulator/gradient_accumulator/accumulators.py", line 1, in <module>
    import tensorflow as tf
  File "/opt/hostedtoolcache/Python/3.8.[16](https://github.com/andreped/GradientAccumulator/actions/runs/4676953980/jobs/8283906385#step:7:17)/x64/lib/python3.8/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.[19](https://github.com/andreped/GradientAccumulator/actions/runs/4676953980/jobs/8283906385#step:7:20).0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.[20](https://github.com/andreped/GradientAccumulator/actions/runs/4676953980/jobs/8283906385#step:7:21).x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

**Comment by andreped** [comment]
Fixed in 67418b95f7ec8403953f72446322ec586b8014ff
